# Generated by Django 3.0.2 on 2020-03-04 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citylist',
            name='periodictask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.PeriodicTask'),
        ),
    ]
